"""
Database models and configuration for AI Trading Platform
"""
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, JSON, Boolean, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import os

# Database configuration
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./trading_platform.db")

# Fix Railway PostgreSQL URL format (postgres:// -> postgresql://)
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Models
class Strategy(Base):
    """Trading strategy generated by AI"""
    __tablename__ = "strategies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True)
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Strategy parameters
    tickers = Column(JSON)  # List of tickers
    entry_conditions = Column(JSON)  # Entry rules
    exit_conditions = Column(JSON)  # Exit rules
    stop_loss_pct = Column(Float)
    take_profit_pct = Column(Float)
    position_size_pct = Column(Float)
    holding_period_days = Column(Integer)

    # AI-generated content
    rationale = Column(Text)
    market_analysis = Column(Text)
    risk_assessment = Column(Text)

    # Strategy type and indicators
    strategy_type = Column(String)  # momentum, mean_reversion, breakout, etc.
    indicators = Column(JSON)  # List of technical indicators used

    # Status
    is_active = Column(Boolean, default=True)
    is_paper_trading = Column(Boolean, default=False)


class BacktestResult(Base):
    """Backtesting results for strategies"""
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, index=True)
    strategy_name = Column(String, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Test parameters
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    initial_capital = Column(Float)
    tickers_tested = Column(JSON)

    # Performance metrics
    total_return_pct = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)

    # Risk metrics
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    max_drawdown_pct = Column(Float)
    volatility = Column(Float, nullable=True)  # Optional field

    # Advanced metrics
    profit_factor = Column(Float)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    largest_win = Column(Float, nullable=True)  # Optional field
    largest_loss = Column(Float, nullable=True)  # Optional field

    # Trade details
    trades = Column(JSON)  # List of all trades executed
    equity_curve = Column(JSON)  # Daily equity values

    # Quality score (calculated)
    quality_score = Column(Float)  # 0-100 composite score

    # Kelly Criterion optimal position sizing
    kelly_criterion = Column(Float, nullable=True)  # Kelly fraction (0-1)
    kelly_position_pct = Column(Float, nullable=True)  # Recommended position %
    kelly_risk_level = Column(String, nullable=True)  # Risk level assessment


class PaperTrade(Base):
    """Paper trading positions and history"""
    __tablename__ = "paper_trades"

    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, index=True)
    strategy_name = Column(String)

    # Trade details
    ticker = Column(String, index=True)
    action = Column(String)  # BUY or SELL
    quantity = Column(Float)
    entry_price = Column(Float)
    exit_price = Column(Float, nullable=True)

    # Timestamps
    entry_date = Column(DateTime, default=datetime.utcnow)
    exit_date = Column(DateTime, nullable=True)

    # Position details
    position_size_usd = Column(Float)
    stop_loss_price = Column(Float)
    take_profit_price = Column(Float)

    # Results
    profit_loss_usd = Column(Float, nullable=True)
    profit_loss_pct = Column(Float, nullable=True)
    is_open = Column(Boolean, default=True)

    # Exit reason
    exit_reason = Column(String, nullable=True)  # stop_loss, take_profit, signal, manual


class PortfolioAllocation(Base):
    """Optimized portfolio allocations"""
    __tablename__ = "portfolio_allocations"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    name = Column(String)

    # Portfolio configuration
    total_capital = Column(Float)
    strategies = Column(JSON)  # List of strategy IDs with allocations

    # Optimization parameters
    optimization_method = Column(String)  # sharpe, min_variance, max_return, etc.
    constraints = Column(JSON)

    # Results
    expected_return = Column(Float)
    expected_volatility = Column(Float)
    expected_sharpe = Column(Float)

    # Allocations
    allocations = Column(JSON)  # {strategy_id: allocation_pct}

    is_active = Column(Boolean, default=True)


class PerformanceLog(Base):
    """Daily performance tracking"""
    __tablename__ = "performance_logs"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, default=datetime.utcnow, index=True)

    # What is being tracked
    entity_type = Column(String)  # strategy, portfolio, paper_trade
    entity_id = Column(Integer, index=True)

    # Daily metrics
    daily_return_pct = Column(Float)
    cumulative_return_pct = Column(Float)
    portfolio_value = Column(Float)
    drawdown_pct = Column(Float)

    # Additional data
    meta_data = Column(JSON)


class AILearning(Base):
    """AI learning history and improvements"""
    __tablename__ = "ai_learning"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # What was learned
    learning_type = Column(String)  # success_pattern, failure_pattern, market_insight
    description = Column(Text)

    # Source data
    strategy_ids = Column(JSON)  # Strategies that contributed to this learning
    performance_data = Column(JSON)

    # Learning insights
    key_insights = Column(JSON)
    recommendations = Column(JSON)

    # Application
    applied_count = Column(Integer, default=0)  # How many times this was used
    confidence_score = Column(Float)  # 0-1


class LivePosition(Base):
    """Live positions in Alpaca account (synced from broker)"""
    __tablename__ = "live_positions"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Position details
    ticker = Column(String, index=True)
    strategy_id = Column(Integer, index=True, nullable=True)
    strategy_name = Column(String, nullable=True)

    # Quantities and prices
    qty = Column(Float)
    entry_price = Column(Float)
    current_price = Column(Float)

    # P&L
    unrealized_pl = Column(Float)
    unrealized_plpc = Column(Float)  # Percent

    # Risk management
    stop_loss_price = Column(Float, nullable=True)
    take_profit_price = Column(Float, nullable=True)

    # Alpaca data
    alpaca_position_id = Column(String, unique=True, index=True)
    alpaca_data = Column(JSON)  # Full Alpaca position response

    # Status
    is_open = Column(Boolean, default=True)
    exit_reason = Column(String, nullable=True)


class TradeExecution(Base):
    """Log of all order executions (complete audit trail)"""
    __tablename__ = "trade_executions"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Order details
    ticker = Column(String, index=True)
    strategy_id = Column(Integer, index=True)
    strategy_name = Column(String)

    # Signal that triggered this
    signal_type = Column(String)  # BUY, SELL, HOLD
    signal_confidence = Column(String)  # HIGH, MEDIUM, LOW
    signal_price = Column(Float)  # Price when signal was generated

    # Order execution
    order_type = Column(String)  # market, limit
    side = Column(String)  # buy, sell
    qty = Column(Float, nullable=True)
    notional = Column(Float, nullable=True)  # Dollar amount

    # Execution details
    filled_qty = Column(Float, nullable=True)
    filled_avg_price = Column(Float, nullable=True)
    commission = Column(Float, nullable=True)

    # Status
    order_status = Column(String)  # new, filled, partially_filled, canceled, rejected
    alpaca_order_id = Column(String, unique=True, index=True)
    alpaca_order_data = Column(JSON)

    # Why this decision was made
    decision_reasoning = Column(Text)
    decision_factors = Column(JSON)


class TradeJustification(Base):
    """Audit log of executed and rejected trade decisions with readable rationale."""
    __tablename__ = "trade_justifications"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    trade_execution_id = Column(Integer, ForeignKey("trade_executions.id"), nullable=True, index=True)
    ticker = Column(String, index=True, nullable=False)
    action = Column(String, nullable=False)  # BUY, SELL, REJECT
    strategy_name = Column(String, nullable=True)
    justification = Column(Text, nullable=False)
    conviction_score = Column(Float, nullable=True)
    kelly_pct = Column(Float, nullable=True)
    regime = Column(String, nullable=True)
    earnings_days_away = Column(Integer, nullable=True)
    rsi = Column(Float, nullable=True)
    sma50_position = Column(String, nullable=True)  # above / below
    confluence_count = Column(Integer, nullable=True)
    rejection_reason = Column(Text, nullable=True)
    decision_factors_json = Column(Text, nullable=True)


class PortfolioSnapshot(Base):
    """Portfolio point-in-time snapshot for equity curve and P&L analytics."""
    __tablename__ = "portfolio_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    equity = Column(Float, nullable=True)
    cash = Column(Float, nullable=True)
    buying_power = Column(Float, nullable=True)
    num_positions = Column(Integer, nullable=True)
    daily_pnl = Column(Float, nullable=True)
    daily_pnl_pct = Column(Float, nullable=True)
    regime = Column(String, nullable=True)
    notes = Column(Text, nullable=True)


class StrategyPerformance(Base):
    """Live strategy performance tracking (vs backtest)"""
    __tablename__ = "strategy_performance"

    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, index=True, unique=True)
    strategy_name = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Backtest baseline (for comparison)
    backtest_sharpe = Column(Float)
    backtest_win_rate = Column(Float)
    backtest_avg_return = Column(Float)
    backtest_max_drawdown = Column(Float)

    # Live performance (updated daily)
    live_sharpe = Column(Float, nullable=True)
    live_win_rate = Column(Float, nullable=True)
    live_avg_return = Column(Float, nullable=True)
    live_max_drawdown = Column(Float, nullable=True)

    # Trade counts
    live_total_trades = Column(Integer, default=0)
    live_winning_trades = Column(Integer, default=0)
    live_losing_trades = Column(Integer, default=0)

    # Performance delta (how different from backtest)
    sharpe_delta = Column(Float, nullable=True)
    win_rate_delta = Column(Float, nullable=True)

    # Status and weighting
    performance_score = Column(Float, nullable=True)  # 0-100
    allocation_weight = Column(Float, default=1.0)  # Multiplier for position sizing
    is_deprecated = Column(Boolean, default=False)
    deprecation_reason = Column(String, nullable=True)

    # Last evaluation
    last_evaluated_at = Column(DateTime, nullable=True)
    next_evaluation_at = Column(DateTime, nullable=True)


class StrategyResearch(Base):
    """Research and validation logs for optimized and AI-generated strategies."""
    __tablename__ = "strategy_research"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    strategy_name = Column(String, index=True)
    source = Column(String)  # optimizer or ai_generated
    params_json = Column(Text)
    backtest_sharpe = Column(Float, nullable=True)
    backtest_return_pct = Column(Float, nullable=True)
    backtest_win_rate = Column(Float, nullable=True)
    backtest_max_dd = Column(Float, nullable=True)
    backtest_trade_count = Column(Integer, nullable=True)
    walk_forward_sharpe = Column(Float, nullable=True)
    walk_forward_return_pct = Column(Float, nullable=True)
    is_deployed = Column(Boolean, default=False)
    deployment_date = Column(DateTime, nullable=True)
    notes = Column(Text, nullable=True)


class AutoTradingState(Base):
    """Autonomous trading system state"""
    __tablename__ = "auto_trading_state"

    id = Column(Integer, primary_key=True, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # System status
    is_enabled = Column(Boolean, default=False)
    is_running = Column(Boolean, default=False)
    last_run_at = Column(DateTime, nullable=True)
    next_run_at = Column(DateTime, nullable=True)

    # Daily metrics
    daily_pnl = Column(Float, default=0.0)
    daily_pnl_pct = Column(Float, default=0.0)
    daily_trades = Column(Integer, default=0)

    # Portfolio state
    portfolio_value = Column(Float)
    cash_balance = Column(Float)
    buying_power = Column(Float)
    num_positions = Column(Integer, default=0)

    # Risk limits
    max_daily_loss_hit = Column(Boolean, default=False)
    circuit_breaker_triggered = Column(Boolean, default=False)
    circuit_breaker_reason = Column(String, nullable=True)

    # Execution stats
    total_signals_generated = Column(Integer, default=0)
    total_trades_executed = Column(Integer, default=0)
    total_trades_rejected = Column(Integer, default=0)

    # Learning stats
    last_reoptimization_at = Column(DateTime, nullable=True)
    strategies_deprecated_count = Column(Integer, default=0)

    # Logs
    recent_activity = Column(JSON)  # Last 10 activities


# =======================
# PAIR TRADING MODELS
# =======================

class PairTradingPair(Base):
    """Store discovered cointegrated pairs with statistics"""
    __tablename__ = "pair_trading_pairs"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Pair identifiers
    stock_a = Column(String, index=True)
    stock_b = Column(String, index=True)

    # Cointegration statistics
    is_cointegrated = Column(Boolean, default=True)
    cointegration_pvalue = Column(Float)
    hedge_ratio = Column(Float)
    correlation = Column(Float)

    # Mean reversion metrics
    hurst_exponent = Column(Float)
    half_life_days = Column(Float)
    adf_pvalue = Column(Float)

    # Quality scoring
    quality_score = Column(Float)  # 0-100

    # Current state
    spread_mean = Column(Float)
    spread_std = Column(Float)
    current_zscore = Column(Float)
    current_signal = Column(String)  # LONG_SPREAD, SHORT_SPREAD, EXIT, HOLD

    # Performance tracking
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_signal_date = Column(DateTime, nullable=True)

    # Configuration
    entry_threshold = Column(Float, default=2.0)
    exit_threshold = Column(Float, default=0.5)
    stop_loss_threshold = Column(Float, default=4.0)

    # Status
    is_active = Column(Boolean, default=True)
    last_tested = Column(DateTime, nullable=True)


class PairTradingPosition(Base):
    """Track open/closed pair trading positions"""
    __tablename__ = "pair_trading_positions"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Link to pair
    pair_id = Column(Integer, index=True)
    stock_a = Column(String, index=True)
    stock_b = Column(String, index=True)

    # Position type
    position_type = Column(String)  # LONG_SPREAD or SHORT_SPREAD

    # Stock A position (long or short)
    shares_a = Column(Float)
    entry_price_a = Column(Float)
    exit_price_a = Column(Float, nullable=True)

    # Stock B position (opposite of A)
    shares_b = Column(Float)
    entry_price_b = Column(Float)
    exit_price_b = Column(Float, nullable=True)

    # Entry details
    entry_date = Column(DateTime, default=datetime.utcnow)
    entry_zscore = Column(Float)
    entry_spread = Column(Float)
    hedge_ratio = Column(Float)

    # Exit details
    exit_date = Column(DateTime, nullable=True)
    exit_zscore = Column(Float, nullable=True)
    exit_spread = Column(Float, nullable=True)
    exit_reason = Column(String, nullable=True)  # mean_reversion, stop_loss, manual

    # Position sizing
    capital_allocated = Column(Float)
    notional_long = Column(Float)
    notional_short = Column(Float)

    # P&L
    pnl_stock_a = Column(Float, nullable=True)
    pnl_stock_b = Column(Float, nullable=True)
    total_pnl = Column(Float, nullable=True)
    return_pct = Column(Float, nullable=True)

    # Transaction costs
    transaction_costs = Column(Float, default=0.0)
    borrowing_costs = Column(Float, default=0.0)

    # Status
    is_open = Column(Boolean, default=True)


class PairScanResult(Base):
    """Store scan history and results"""
    __tablename__ = "pair_scan_results"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Scan parameters
    universe_name = Column(String)  # tech, finance, healthcare, etc.
    tickers_scanned = Column(JSON)  # List of tickers
    pairs_tested = Column(Integer)
    period = Column(String)  # 1y, 2y, etc.

    # Scan configuration
    correlation_threshold = Column(Float)
    significance_level = Column(Float)
    min_quality_score = Column(Float)

    # Results summary
    pairs_found = Column(Integer)
    avg_quality_score = Column(Float, nullable=True)
    best_pair = Column(String, nullable=True)  # "AAPL/MSFT"
    best_quality_score = Column(Float, nullable=True)

    # Detailed results
    results = Column(JSON)  # Full list of discovered pairs

    # Execution time
    scan_duration_seconds = Column(Float, nullable=True)


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
