"""
Database models and configuration for AI Trading Platform
"""
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, JSON, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import os

# Database configuration
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./trading_platform.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Models
class Strategy(Base):
    """Trading strategy generated by AI"""
    __tablename__ = "strategies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True)
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Strategy parameters
    tickers = Column(JSON)  # List of tickers
    entry_conditions = Column(JSON)  # Entry rules
    exit_conditions = Column(JSON)  # Exit rules
    stop_loss_pct = Column(Float)
    take_profit_pct = Column(Float)
    position_size_pct = Column(Float)
    holding_period_days = Column(Integer)

    # AI-generated content
    rationale = Column(Text)
    market_analysis = Column(Text)
    risk_assessment = Column(Text)

    # Strategy type and indicators
    strategy_type = Column(String)  # momentum, mean_reversion, breakout, etc.
    indicators = Column(JSON)  # List of technical indicators used

    # Status
    is_active = Column(Boolean, default=True)
    is_paper_trading = Column(Boolean, default=False)


class BacktestResult(Base):
    """Backtesting results for strategies"""
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, index=True)
    strategy_name = Column(String, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Test parameters
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    initial_capital = Column(Float)
    tickers_tested = Column(JSON)

    # Performance metrics
    total_return_pct = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)

    # Risk metrics
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    max_drawdown_pct = Column(Float)
    volatility = Column(Float)

    # Advanced metrics
    profit_factor = Column(Float)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    largest_win = Column(Float)
    largest_loss = Column(Float)

    # Trade details
    trades = Column(JSON)  # List of all trades executed
    equity_curve = Column(JSON)  # Daily equity values

    # Quality score (calculated)
    quality_score = Column(Float)  # 0-100 composite score


class PaperTrade(Base):
    """Paper trading positions and history"""
    __tablename__ = "paper_trades"

    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, index=True)
    strategy_name = Column(String)

    # Trade details
    ticker = Column(String, index=True)
    action = Column(String)  # BUY or SELL
    quantity = Column(Float)
    entry_price = Column(Float)
    exit_price = Column(Float, nullable=True)

    # Timestamps
    entry_date = Column(DateTime, default=datetime.utcnow)
    exit_date = Column(DateTime, nullable=True)

    # Position details
    position_size_usd = Column(Float)
    stop_loss_price = Column(Float)
    take_profit_price = Column(Float)

    # Results
    profit_loss_usd = Column(Float, nullable=True)
    profit_loss_pct = Column(Float, nullable=True)
    is_open = Column(Boolean, default=True)

    # Exit reason
    exit_reason = Column(String, nullable=True)  # stop_loss, take_profit, signal, manual


class PortfolioAllocation(Base):
    """Optimized portfolio allocations"""
    __tablename__ = "portfolio_allocations"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    name = Column(String)

    # Portfolio configuration
    total_capital = Column(Float)
    strategies = Column(JSON)  # List of strategy IDs with allocations

    # Optimization parameters
    optimization_method = Column(String)  # sharpe, min_variance, max_return, etc.
    constraints = Column(JSON)

    # Results
    expected_return = Column(Float)
    expected_volatility = Column(Float)
    expected_sharpe = Column(Float)

    # Allocations
    allocations = Column(JSON)  # {strategy_id: allocation_pct}

    is_active = Column(Boolean, default=True)


class PerformanceLog(Base):
    """Daily performance tracking"""
    __tablename__ = "performance_logs"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, default=datetime.utcnow, index=True)

    # What is being tracked
    entity_type = Column(String)  # strategy, portfolio, paper_trade
    entity_id = Column(Integer, index=True)

    # Daily metrics
    daily_return_pct = Column(Float)
    cumulative_return_pct = Column(Float)
    portfolio_value = Column(Float)
    drawdown_pct = Column(Float)

    # Additional data
    meta_data = Column(JSON)


class AILearning(Base):
    """AI learning history and improvements"""
    __tablename__ = "ai_learning"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # What was learned
    learning_type = Column(String)  # success_pattern, failure_pattern, market_insight
    description = Column(Text)

    # Source data
    strategy_ids = Column(JSON)  # Strategies that contributed to this learning
    performance_data = Column(JSON)

    # Learning insights
    key_insights = Column(JSON)
    recommendations = Column(JSON)

    # Application
    applied_count = Column(Integer, default=0)  # How many times this was used
    confidence_score = Column(Float)  # 0-1


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
